runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_NAME: Al-Yusna
  APP_ENV: production
  APP_DEBUG: false
  LOG_CHANNEL: stack
  LOG_LEVEL: critical
  APP_KEY: YOUR_APP_KEY
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie